### ISSUE TITLE
I demand more personal touch

### ISSUE THREAD

**Issue by valerybugakov** [alxnddr/website#1]
The website currently doesn't provide any information about your interests and personality. THIS IS NOT GOOD 🙂
Would it be possible to fix in the next release?

**Comment by alxnddr** [comment]
@valerybugakov good point! However, I intentionally kept strictly professional since the only reason I needed it was to prove that I am a software engineer to Uruguayan Immigration Authority, otherwise, they don't believe me no matter if I have an entity, pay taxes, etc. So adding more personal info can get in the way of acknowledging me as a coder 🤷‍♂️

**Comment by valerybugakov** [comment]
🥲🫠 oh, I see 🥲🫠
